from pathlib import Path
import re
p = Path('/home/ubuntu/mini-erp-bia/client/src/pages/Home.tsx')
s = p.read_text()
new = r'''function Reports() {
  const [range, setRange] = useState<"7d" | "30d" | "90d">("30d");
  const days = range === "7d" ? 7 : range === "90d" ? 90 : 30;
  const from = new Date(Date.now() - days * 86400000);
  const input = { from, to: new Date() };
  const production = trpc.reports.production.useQuery(input);
  const inventory = trpc.reports.inventory.useQuery(input);
  const productionData = production.data;
  const inventoryData = inventory.data;
  const maxDay = Math.max(...(productionData?.byDay ?? []).map(item => item.actualQuantity), 1);
  const maxMovement = Math.max(...(inventoryData?.movementsByDay ?? []).map(item => Math.max(item.inbound, item.outbound)), 1);
  const statusLabels: Record<string, string> = { planned: "Đã lập kế hoạch", in_progress: "Đang sản xuất", completed: "Hoàn thành", cancelled: "Đã hủy" };
  const loading = production.isLoading || inventory.isLoading;
  const error = production.isError || inventory.isError;
  return <div>
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-amber-300/70">THỐNG KÊ / BÁO CÁO</p><h2 className="font-display text-3xl font-bold">Báo cáo Sản xuất & Kho bãi</h2><p className="mt-2 text-sm text-slate-500">Phân tích trực quan theo dữ liệu thực tế và quyền truy cập của tài khoản.</p></div><select value={range} onChange={e => setRange(e.target.value as typeof range)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-slate-200"><option value="7d">7 ngày gần nhất</option><option value="30d">30 ngày gần nhất</option><option value="90d">90 ngày gần nhất</option></select></div>
    {loading ? <div className="glass rounded-2xl p-12 text-center text-sm text-slate-400">Đang tổng hợp báo cáo...</div> : error ? <div className="glass rounded-2xl border border-red-400/20 p-12 text-center text-sm text-red-300">Không thể tải báo cáo. Vui lòng thử lại sau.</div> : <>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Tổng số lô sản xuất</p><p className="mt-2 font-display text-3xl font-bold text-amber-300">{productionData?.totalBatches ?? 0}</p><p className="mt-1 text-xs text-slate-500">Trong khoảng đã chọn</p></div><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Sản lượng kế hoạch</p><p className="mt-2 font-display text-3xl font-bold">{(productionData?.plannedQuantity ?? 0).toLocaleString("vi-VN")} kg</p></div><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Tồn kho hiện tại</p><p className="mt-2 font-display text-3xl font-bold text-teal-300">{(inventoryData?.totalStock ?? 0).toLocaleString("vi-VN")} kg</p></div><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Mặt hàng dưới ngưỡng</p><p className="mt-2 font-display text-3xl font-bold text-red-300">{inventoryData?.lowStockCount ?? 0}</p></div></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.9fr]">
        <section className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><div><h3 className="font-display text-lg font-bold">Sản lượng thực tế theo ngày</h3><p className="text-xs text-slate-500">Tổng sản lượng ghi nhận theo lô</p></div><span className="rounded-full bg-amber-300/10 px-3 py-1 text-xs text-amber-200">Sản xuất</span></div>{productionData?.byDay.length ? <div className="mt-6 flex h-56 items-end gap-2 overflow-hidden">{productionData.byDay.map(item => <div key={item.date} className="flex min-w-[24px] flex-1 flex-col items-center gap-2"><div title={`${item.date}: ${item.actualQuantity.toLocaleString("vi-VN")} kg`} className="w-full rounded-t-md bg-gradient-to-t from-amber-500/80 to-yellow-200" style={{ height: `${Math.max(8, item.actualQuantity / maxDay * 100)}%` }} /><span className="text-[10px] text-slate-500">{item.date.slice(5)}</span></div>)}</div> : <p className="mt-10 text-center text-sm text-slate-500">Chưa có dữ liệu sản xuất trong khoảng này.</p>}</section>
        <section className="glass rounded-2xl p-5"><h3 className="font-display text-lg font-bold">Trạng thái lô sản xuất</h3><p className="text-xs text-slate-500">Phân bổ theo trạng thái hiện tại</p><div className="mt-5 space-y-3">{productionData?.byStatus.length ? productionData.byStatus.map(item => <div key={item.status}><div className="mb-1 flex justify-between text-xs"><span className="text-slate-300">{statusLabels[item.status] ?? item.status}</span><span className="text-amber-200">{item.count} lô</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-teal-300" style={{ width: `${Math.max(6, item.count / Math.max(productionData.totalBatches, 1) * 100)}%` }} /></div></div>) : <p className="mt-10 text-center text-sm text-slate-500">Chưa có lô sản xuất.</p>}</div></section>
      </div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_1.2fr]"><section className="glass rounded-2xl p-5"><h3 className="font-display text-lg font-bold">Tồn kho theo nguyên liệu</h3><p className="text-xs text-slate-500">Top mặt hàng có số lượng tồn cao nhất</p><div className="mt-5 space-y-4">{inventoryData?.topStock.length ? inventoryData.topStock.map(item => <div key={item.id}><div className="mb-1 flex justify-between text-xs"><span className="truncate pr-3 text-slate-300">{item.name}</span><span className="text-amber-200">{Number(item.stockQuantity).toLocaleString("vi-VN")} {item.unit}</span></div><div className="h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-teal-400 to-cyan-300" style={{ width: `${Math.max(4, Number(item.stockQuantity) / Math.max(Number(inventoryData.topStock[0]?.stockQuantity ?? 1), 1) * 100)}%` }} /></div></div>) : <p className="mt-10 text-center text-sm text-slate-500">Chưa có dữ liệu tồn kho.</p>}</div></section><section className="glass rounded-2xl p-5"><h3 className="font-display text-lg font-bold">Nhập – xuất kho theo ngày</h3><p className="text-xs text-slate-500">Khối lượng giao dịch trong khoảng đã chọn</p>{inventoryData?.movementsByDay.length ? <div className="mt-6 flex h-56 items-end gap-2 overflow-hidden">{inventoryData.movementsByDay.map(item => <div key={item.date} className="flex min-w-[30px] flex-1 items-end justify-center gap-1"><div title={`Nhập ${item.inbound}`} className="w-1/2 rounded-t bg-teal-300/80" style={{ height: `${Math.max(6, item.inbound / maxMovement * 100)}%` }} /><div title={`Xuất ${item.outbound}`} className="w-1/2 rounded-t bg-rose-300/80" style={{ height: `${Math.max(6, item.outbound / maxMovement * 100)}%` }} /></div>)}</div> : <p className="mt-10 text-center text-sm text-slate-500">Chưa có giao dịch kho.</p>}<div className="mt-4 flex gap-4 text-xs text-slate-500"><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-teal-300" />Nhập kho</span><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-rose-300" />Xuất kho</span></div></section></div>
    </>}
  </div>;
}'''
s2 = re.sub(r'function Reports\(\) \{.*?\n?\}', new, s, count=1, flags=re.S)
if s2 == s:
    raise SystemExit('Reports function not found')
p.write_text(s2)
