import { useMemo, useState } from "react";
import { Boxes, Plus } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function InventoryPanel() {
  const [cursor, setCursor] = useState<number>(); const [search, setSearch] = useState(""); const pageInput = useMemo(() => ({ limit: 100, cursor }), [cursor]); const page = trpc.ingredients.page.useQuery(pageInput); const create = trpc.ingredients.create.useMutation({ onSuccess: () => { void page.refetch(); toast.success("Đã thêm nguyên liệu"); }, onError: error => toast.error(error.message) }); const [form, setForm] = useState({ name: "", quantity: "" }); const rows = (page.data?.items ?? []).filter((item: any) => item.name.toLowerCase().includes(search.toLowerCase())); const save = async () => { if (!form.name.trim()) return toast.error("Vui lòng nhập tên nguyên liệu"); await create.mutateAsync({ name: form.name.trim(), unit: "kg", stockQuantity: Number(form.quantity) || 0, lowStockThreshold: 100 }); setForm({ name: "", quantity: "" }); };
  return <section className="space-y-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-amber-300/70">VẬN HÀNH / KHO</p><h2 className="mt-1 flex items-center gap-3 font-display text-3xl font-bold"><Boxes className="text-amber-300" size={27} />Kho nguyên liệu</h2><p className="mt-2 text-sm text-slate-500">Theo dõi tồn kho, mức cảnh báo và lịch sử dữ liệu tập trung.</p></div></div><div className="glass rounded-2xl p-5"><div className="grid gap-2 sm:grid-cols-[1fr_180px_auto]"><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Tên nguyên liệu" className="border-white/10 bg-white/5" /><Input value={form.quantity} onChange={event => setForm({ ...form, quantity: event.target.value })} type="number" placeholder="Số lượng (kg)" className="border-white/10 bg-white/5" /><Button onClick={() => void save()} disabled={create.isPending} className="bg-amber-400 text-[#08111f] hover:bg-amber-300"><Plus size={16} />{create.isPending ? "Đang lưu..." : "Nhập kho"}</Button></div><div className="mt-5 flex gap-3"><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Tìm nguyên liệu..." className="max-w-md border-white/10 bg-white/5" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-3 py-3">Nguyên liệu</th><th className="px-3 py-3">Mã vật tư</th><th className="px-3 py-3">Tồn hiện tại</th><th className="px-3 py-3">Mức cảnh báo</th><th className="px-3 py-3">Trạng thái</th></tr></thead><tbody>{page.isLoading ? <tr><td colSpan={5} className="px-3 py-8 text-center text-slate-500">Đang tải kho...</td></tr> : rows.map((item: any) => { const low = Number(item.stockQuantity) <= Number(item.lowStockThreshold); return <tr key={item.id} className="border-t border-white/5"><td className="px-3 py-3 font-semibold text-slate-200">{item.name}</td><td className="px-3 py-3 text-slate-500">NL-{String(item.id).padStart(4, "0")}</td><td className="px-3 py-3 text-slate-200">{Number(item.stockQuantity).toLocaleString("vi-VN")} {item.unit}</td><td className="px-3 py-3 text-slate-400">{Number(item.lowStockThreshold).toLocaleString("vi-VN")}</td><td className={`px-3 py-3 ${low ? "text-amber-200" : "text-teal-200"}`}>{low ? "Sắp hết" : "Đủ tồn"}</td></tr>; })}</tbody></table></div>{page.data?.nextCursor && <div className="mt-4 text-right"><Button variant="outline" onClick={() => setCursor(page.data?.nextCursor ?? undefined)} className="border-white/10 bg-white/5">Tải thêm</Button></div>}</div></section>;
}
