import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";

export default function ReportsPanel() {
  const [range, setRange] = useState<"7d" | "30d" | "90d">("30d");
  const [module, setModule] = useState<"all" | "production" | "inventory">("all");
  const input = useMemo(() => { const days = range === "7d" ? 7 : range === "90d" ? 90 : 30; const to = new Date(); return { from: new Date(to.getTime() - days * 86400000), to }; }, [range]);
  const production = trpc.reports.production.useQuery(input, { enabled: module !== "inventory" });
  const inventory = trpc.reports.inventory.useQuery(input, { enabled: module !== "production" });
  const costing = trpc.reports.costing.useQuery();
  const productionData = production.data;
  const inventoryData = inventory.data;
  const maxDay = Math.max(...(productionData?.byDay ?? []).map(item => item.actualQuantity), 1);
  const maxMovement = Math.max(...(inventoryData?.movementsByDay ?? []).map(item => Math.max(item.inbound, item.outbound)), 1);
  const statusLabels: Record<string, string> = { planned: "Đã lập kế hoạch", in_progress: "Đang sản xuất", completed: "Hoàn thành", cancelled: "Đã hủy" };
  const loading = production.isLoading || inventory.isLoading;
  const error = production.isError || inventory.isError;
  return <div>
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-amber-300/70">THỐNG KÊ / BÁO CÁO</p><h2 className="font-display text-3xl font-bold">Báo cáo Sản xuất & Kho bãi</h2><p className="mt-2 text-sm text-slate-500">Phân tích trực quan theo dữ liệu thực tế và quyền truy cập của tài khoản.</p></div><div className="flex flex-wrap gap-2"><select value={module} onChange={e => setModule(e.target.value as typeof module)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-slate-200"><option value="all">Tất cả phân hệ</option><option value="production">Chỉ Sản xuất</option><option value="inventory">Chỉ Kho bãi</option></select><select value={range} onChange={e => setRange(e.target.value as typeof range)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-slate-200"><option value="7d">7 ngày gần nhất</option><option value="30d">30 ngày gần nhất</option><option value="90d">90 ngày gần nhất</option></select></div></div>
    {loading ? <div className="glass rounded-2xl p-12 text-center text-sm text-slate-400">Đang tổng hợp báo cáo...</div> : error ? <div className="glass rounded-2xl border border-red-400/20 p-12 text-center text-sm text-red-300">Không thể tải báo cáo. Vui lòng thử lại sau.</div> : <>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(module !== "inventory") && <><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Tổng số lô sản xuất</p><p className="mt-2 font-display text-3xl font-bold text-amber-300">{productionData?.totalBatches ?? 0}</p><p className="mt-1 text-xs text-slate-500">Trong khoảng đã chọn</p></div><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Sản lượng kế hoạch</p><p className="mt-2 font-display text-3xl font-bold">{(productionData?.plannedQuantity ?? 0).toLocaleString("vi-VN")} kg</p></div></>}{(module !== "production") && <><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Tồn kho hiện tại</p><p className="mt-2 font-display text-3xl font-bold text-teal-300">{(inventoryData?.totalStock ?? 0).toLocaleString("vi-VN")} kg</p></div><div className="glass rounded-2xl p-5"><p className="text-xs text-slate-500">Mặt hàng dưới ngưỡng</p><p className="mt-2 font-display text-3xl font-bold text-red-300">{inventoryData?.lowStockCount ?? 0}</p></div></>}</div>
      {module !== "inventory" && <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><section className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><div><h3 className="font-display text-lg font-bold">Sản lượng thực tế theo ngày</h3><p className="text-xs text-slate-500">Tổng sản lượng ghi nhận theo lô</p></div><span className="rounded-full bg-amber-300/10 px-3 py-1 text-xs text-amber-200">Sản xuất</span></div>{productionData?.byDay.length ? <div className="mt-6 flex h-56 items-end gap-2 overflow-hidden">{productionData.byDay.map(item => <div key={item.date} className="flex min-w-[24px] flex-1 flex-col items-center gap-2"><div title={`${item.date}: ${item.actualQuantity.toLocaleString("vi-VN")} kg`} className="w-full rounded-t-md bg-gradient-to-t from-amber-500/80 to-yellow-200" style={{ height: `${Math.max(8, item.actualQuantity / maxDay * 100)}%` }} /><span className="text-[10px] text-slate-500">{item.date.slice(5)}</span></div>)}</div> : <p className="mt-10 text-center text-sm text-slate-500">Chưa có dữ liệu sản xuất trong khoảng này.</p>}</section><section className="glass rounded-2xl p-5"><h3 className="font-display text-lg font-bold">Trạng thái lô sản xuất</h3><p className="text-xs text-slate-500">Phân bổ theo trạng thái hiện tại</p><div className="mt-5 space-y-3">{productionData?.byStatus.length ? productionData.byStatus.map(item => <div key={item.status}><div className="mb-1 flex justify-between text-xs"><span className="text-slate-300">{statusLabels[item.status] ?? item.status}</span><span className="text-amber-200">{item.count} lô</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-teal-300" style={{ width: `${Math.max(6, item.count / Math.max(productionData.totalBatches, 1) * 100)}%` }} /></div></div>) : <p className="mt-10 text-center text-sm text-slate-500">Chưa có lô sản xuất.</p>}</div></section></div>}
      {module !== "production" && <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_1.2fr]"><section className="glass rounded-2xl p-5"><h3 className="font-display text-lg font-bold">Tồn kho theo nguyên liệu</h3><p className="text-xs text-slate-500">Top mặt hàng có số lượng tồn cao nhất</p><div className="mt-5 space-y-4">{inventoryData?.topStock.length ? inventoryData.topStock.map(item => <div key={item.id}><div className="mb-1 flex justify-between text-xs"><span className="truncate pr-3 text-slate-300">{item.name}</span><span className="text-amber-200">{Number(item.stockQuantity).toLocaleString("vi-VN")} {item.unit}</span></div><div className="h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-teal-400 to-cyan-300" style={{ width: `${Math.max(4, Number(item.stockQuantity) / Math.max(Number(inventoryData.topStock[0]?.stockQuantity ?? 1), 1) * 100)}%` }} /></div></div>) : <p className="mt-10 text-center text-sm text-slate-500">Chưa có dữ liệu tồn kho.</p>}</div></section><section className="glass rounded-2xl p-5"><h3 className="font-display text-lg font-bold">Nhập – xuất kho theo ngày</h3><p className="text-xs text-slate-500">Khối lượng giao dịch trong khoảng đã chọn</p>{inventoryData?.movementsByDay.length ? <div className="mt-6 flex h-56 items-end gap-2 overflow-hidden">{inventoryData.movementsByDay.map(item => <div key={item.date} className="flex min-w-[30px] flex-1 items-end justify-center gap-1"><div title={`Nhập ${item.inbound}`} className="w-1/2 rounded-t bg-teal-300/80" style={{ height: `${Math.max(6, item.inbound / maxMovement * 100)}%` }} /><div title={`Xuất ${item.outbound}`} className="w-1/2 rounded-t bg-rose-300/80" style={{ height: `${Math.max(6, item.outbound / maxMovement * 100)}%` }} /></div>)}</div> : <p className="mt-10 text-center text-sm text-slate-500">Chưa có giao dịch kho.</p>}<div className="mt-4 flex gap-4 text-xs text-slate-500"><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-teal-300" />Nhập kho</span><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-rose-300" />Xuất kho</span></div></section></div>}
      {module !== "inventory" && productionData?.byStep?.length ? <section className="glass mt-5 rounded-2xl p-5"><h3 className="font-display text-lg font-bold">Tiến độ theo công đoạn</h3><p className="text-xs text-slate-500">Đường hóa, lên men, lọc và đóng chai trong các lô đã chọn</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{productionData.byStep.map(item => <div key={item.stepType} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><p className="text-sm font-semibold text-slate-200">{{ mashing: "Đường hóa", fermentation: "Lên men", filtration: "Lọc", bottling: "Đóng chai" }[item.stepType] ?? item.stepType}</p><p className="mt-2 text-xs text-slate-500">{item.total} bước</p><div className="mt-3 flex gap-1"><span title="Chờ xử lý" className="h-2 flex-1 rounded-full bg-slate-500" style={{ opacity: item.pending ? 1 : .2 }} /><span title="Đang thực hiện" className="h-2 flex-1 rounded-full bg-amber-300" style={{ opacity: item.inProgress ? 1 : .2 }} /><span title="Hoàn thành" className="h-2 flex-1 rounded-full bg-teal-300" style={{ opacity: item.completed ? 1 : .2 }} /></div><p className="mt-2 text-[11px] text-slate-500">{item.completed} hoàn thành · {item.inProgress} đang làm</p></div>)}</div></section> : null}
      <section className="glass mt-5 rounded-2xl p-5"><div className="flex items-center justify-between"><div><h3 className="font-display text-lg font-bold">Định mức & Giá vốn</h3><p className="text-xs text-slate-500">Chi phí ước tính từ định mức và đơn giá nhập gần nhất</p></div><span className="rounded-full bg-teal-300/10 px-3 py-1 text-xs text-teal-200">{costing.data?.recipes.length ?? 0} công thức</span></div>{costing.isLoading ? <p className="mt-6 text-sm text-slate-500">Đang tính giá vốn...</p> : costing.data?.batches.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{costing.data.batches.slice(0, 8).map(batch => <div key={batch.id} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><p className="text-sm font-semibold text-slate-200">{batch.batchCode}</p><p className="mt-1 text-xs text-slate-500">{batch.actualQuantity || batch.plannedQuantity} kg · {batch.status}</p><p className="mt-3 text-lg font-bold text-amber-200">{Number(batch.estimatedCost).toLocaleString("vi-VN")} ₫</p><p className="mt-1 text-[11px] text-slate-500">Giá vốn ước tính</p></div>)}</div> : <p className="mt-6 text-sm text-slate-500">Chưa đủ định mức hoặc đơn giá nhập để tính giá vốn.</p>}</section>
    </>}
  </div>;
}
