import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { getDb, dashboardSummary, listEmployees, listAttendanceRecords, listLeaveRequests, calculateInclusiveLeaveDays, listIngredients, listIngredientsPage, listLowStockIngredients, listInventoryTransactions, listBeerTypes, listRecipes, listProductionBatches, listProductionSteps, listCustomers, listProducts, listSalesOrders, listAuditLogs, listWorkflowTasks, listQcStandards, listQcResults, selectQcStandardForBeerType, getCrossSheetLinks, getProductionReport, getInventoryReport, listFinanceAccounts, listFinanceTransactions, listReceivables, listPayables, summarizeFinanceTransactions, summarizeOutstanding, listSuppliers, listPurchaseOrders, listPurchaseOrderItems, summarizePurchaseOrders } from "./db";
import { employees, attendanceRecords, leaveRequests, ingredients, inventoryTransactions, beerTypes, recipes, productionBatches, productionSteps, customers, beerProducts, salesOrders, salesOrderItems, users, auditLogs, workflowTasks, qcStandards, qcResults, deviceSessions, financeAccounts, financeTransactions, receivables, payables, suppliers, purchaseOrders, purchaseOrderItems } from "../drizzle/schema";
import { z } from "zod";
import { and, desc, eq } from "drizzle-orm";
import { getRequestMeta, recordAudit } from "./erp-security";

const idInput = z.object({ id: z.number().int().positive() });
const ingredientInput = z.object({ name: z.string().min(1), unit: z.string().min(1), stockQuantity: z.number().nonnegative(), lowStockThreshold: z.number().nonnegative(), supplier: z.string().optional(), notes: z.string().optional() });
const beerInput = z.object({ name: z.string().min(1), description: z.string().optional(), abv: z.number().nonnegative(), color: z.string().optional() });
const customerInput = z.object({ name: z.string().min(1), phone: z.string().optional(), address: z.string().optional(), provinceCode: z.string().max(16).optional(), districtCode: z.string().max(16).optional(), email: z.string().optional(), notes: z.string().optional() });
const employeeInput = z.object({ employeeCode: z.string().min(1).max(40), fullName: z.string().min(1).max(160), phone: z.string().max(40).optional(), email: z.string().email().optional().or(z.literal("")), address: z.string().optional(), department: z.string().min(1).max(120), position: z.string().min(1).max(120), employmentStatus: z.enum(["active", "on_leave", "terminated"]).default("active"), hireDate: z.coerce.date().optional(), notes: z.string().optional() });
const attendanceInput = z.object({ employeeId: z.number().int().positive(), workDate: z.coerce.date(), status: z.enum(["present", "late", "absent", "leave", "holiday"]).default("present"), checkIn: z.coerce.date().optional(), checkOut: z.coerce.date().optional(), note: z.string().optional() });
const leaveCreateInput = z.object({ employeeId: z.number().int().positive(), leaveType: z.enum(["annual", "sick", "unpaid", "other"]).default("annual"), startDate: z.coerce.date(), endDate: z.coerce.date(), reason: z.string().optional() });
const financeAccountInput = z.object({ code: z.string().min(1).max(40), name: z.string().min(1).max(160), accountType: z.enum(["cash", "bank", "other"]).default("cash"), openingBalance: z.number().nonnegative().default(0) });
const financeTransactionInput = z.object({ transactionCode: z.string().min(1).max(80), accountId: z.number().int().positive(), type: z.enum(["income", "expense"]), category: z.string().min(1).max(120), amount: z.number().positive(), transactionDate: z.coerce.date(), counterparty: z.string().max(180).optional(), referenceType: z.string().max(80).optional(), referenceId: z.number().int().positive().optional(), status: z.enum(["draft", "posted", "cancelled"]).default("posted"), note: z.string().optional() });
const receivableInput = z.object({ documentCode: z.string().min(1).max(80), customerId: z.number().int().positive().optional(), orderId: z.number().int().positive().optional(), dueDate: z.coerce.date().optional(), amount: z.number().positive(), note: z.string().optional() });
const payableInput = z.object({ documentCode: z.string().min(1).max(80), supplierName: z.string().min(1).max(180), dueDate: z.coerce.date().optional(), amount: z.number().positive(), note: z.string().optional() });
const supplierInput = z.object({ supplierCode: z.string().min(1).max(40), name: z.string().min(1).max(180), phone: z.string().max(40).optional(), email: z.string().email().optional().or(z.literal("")), address: z.string().optional(), taxCode: z.string().max(40).optional() });
const purchaseOrderInput = z.object({ purchaseCode: z.string().min(1).max(80), supplierId: z.number().int().positive(), expectedAt: z.coerce.date().optional(), note: z.string().optional(), items: z.array(z.object({ ingredientId: z.number().int().positive(), quantity: z.number().positive(), unitPrice: z.number().nonnegative() })).min(1).max(500) });

const requireAdmin = protectedProcedure.use(({ ctx, next }) => {
  if (ctx.user.role !== "admin") throw new Error("Bạn không có quyền truy cập khu vực quản trị");
  return next();
});

function assertOwner(row: { createdBy?: number | null } | undefined, ctx: { user: { id: number; role: string } }) {
  if (!row) throw new Error("Không tìm thấy bản ghi");
  if (ctx.user.role !== "admin" && row.createdBy !== ctx.user.id) throw new Error("Bạn không có quyền sửa bản ghi này");
}

export function evaluateQcValue(value: number, min: number | null, max: number | null): "pass" | "fail" {
  return (min !== null && value < min) || (max !== null && value > max) ? "fail" : "pass";
}

export function resolveQcThresholdForBatch<T extends { beerTypeId: number }, S extends { beerTypeId: number; fieldKey: string }>(batch: T, standards: S[], fieldKey: string) {
  return selectQcStandardForBeerType(standards, batch.beerTypeId, fieldKey);
}

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  dashboard: router({ summary: protectedProcedure.query(() => dashboardSummary()) }),
  finance: router({
    accounts: protectedProcedure.query(({ ctx }) => listFinanceAccounts(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    transactions: protectedProcedure.input(z.object({ type: z.enum(["income", "expense"]).optional() }).optional()).query(({ input, ctx }) => listFinanceTransactions(ctx.user.role === "admin" ? undefined : ctx.user.id, input?.type)),
    summary: protectedProcedure.query(async ({ ctx }) => { const ownerId = ctx.user.role === "admin" ? undefined : ctx.user.id; const [transactions, receivableRows, payableRows] = await Promise.all([listFinanceTransactions(ownerId), listReceivables(ownerId), listPayables(ownerId)]); return { ...summarizeFinanceTransactions(transactions), receivablesOutstanding: summarizeOutstanding(receivableRows), payablesOutstanding: summarizeOutstanding(payableRows) }; }),
    createAccount: protectedProcedure.input(financeAccountInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(financeAccounts).values({ ...input, openingBalance: input.openingBalance.toString(), currentBalance: input.openingBalance.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "finance_accounts", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, accountId: row.insertId }; }),
    createTransaction: protectedProcedure.input(financeTransactionInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const account = (await db.select().from(financeAccounts).where(eq(financeAccounts.id, input.accountId)).limit(1))[0]; assertOwner(account, ctx); if (account.status !== "active") throw new Error("Tài khoản quỹ đã ngừng hoạt động"); const [row] = await db.insert(financeTransactions).values({ ...input, amount: input.amount.toString(), transactionDate: input.transactionDate, createdBy: ctx.user.id }); if (input.status === "posted") { const delta = input.type === "income" ? input.amount : -input.amount; await db.update(financeAccounts).set({ currentBalance: (Number(account.currentBalance) + delta).toFixed(2) }).where(eq(financeAccounts.id, input.accountId)); } await recordAudit({ tableName: "finance_transactions", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, transactionId: row.insertId }; }),
    createReceivable: protectedProcedure.input(receivableInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(receivables).values({ ...input, amount: input.amount.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "receivables", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, receivableId: row.insertId }; }),
    createPayable: protectedProcedure.input(payableInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(payables).values({ ...input, amount: input.amount.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "payables", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, payableId: row.insertId }; }),
    settleReceivable: protectedProcedure.input(idInput.merge(z.object({ paidAmount: z.number().nonnegative() }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(receivables).where(eq(receivables.id, input.id)).limit(1))[0]; assertOwner(current, ctx); if (input.paidAmount > Number(current.amount)) throw new Error("Số tiền thanh toán vượt giá trị phải thu"); const status = input.paidAmount === 0 ? "open" : input.paidAmount >= Number(current.amount) ? "paid" : "partial"; await db.update(receivables).set({ paidAmount: input.paidAmount.toString(), status }).where(eq(receivables.id, input.id)); await recordAudit({ tableName: "receivables", recordId: input.id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: { paidAmount: input.paidAmount, status }, meta: getRequestMeta(ctx.req) }); return { success: true, status }; }),
    settlePayable: protectedProcedure.input(idInput.merge(z.object({ paidAmount: z.number().nonnegative() }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(payables).where(eq(payables.id, input.id)).limit(1))[0]; assertOwner(current, ctx); if (input.paidAmount > Number(current.amount)) throw new Error("Số tiền thanh toán vượt giá trị phải trả"); const status = input.paidAmount === 0 ? "open" : input.paidAmount >= Number(current.amount) ? "paid" : "partial"; await db.update(payables).set({ paidAmount: input.paidAmount.toString(), status }).where(eq(payables.id, input.id)); await recordAudit({ tableName: "payables", recordId: input.id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: { paidAmount: input.paidAmount, status }, meta: getRequestMeta(ctx.req) }); return { success: true, status }; }),
  }),
  purchasing: router({
    suppliers: protectedProcedure.query(({ ctx }) => listSuppliers(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    orders: protectedProcedure.query(({ ctx }) => listPurchaseOrders(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    orderItems: protectedProcedure.input(idInput).query(({ input }) => listPurchaseOrderItems(input.id)),
    summary: protectedProcedure.query(({ ctx }) => listPurchaseOrders(ctx.user.role === "admin" ? undefined : ctx.user.id).then(summarizePurchaseOrders)),
    createSupplier: protectedProcedure.input(supplierInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(suppliers).values({ ...input, createdBy: ctx.user.id }); await recordAudit({ tableName: "suppliers", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, supplierId: row.insertId }; }),
    createOrder: protectedProcedure.input(purchaseOrderInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const supplier = (await db.select().from(suppliers).where(eq(suppliers.id, input.supplierId)).limit(1))[0]; assertOwner(supplier, ctx); const items = input.items.map(item => ({ ...item, total: item.quantity * item.unitPrice })); const subtotal = items.reduce((sum, item) => sum + item.total, 0); const [order] = await db.insert(purchaseOrders).values({ purchaseCode: input.purchaseCode, supplierId: input.supplierId, expectedAt: input.expectedAt, note: input.note, subtotal: subtotal.toString(), total: subtotal.toString(), createdBy: ctx.user.id }); await db.insert(purchaseOrderItems).values(items.map(item => ({ orderId: order.insertId, ingredientId: item.ingredientId, quantity: item.quantity.toString(), unitPrice: item.unitPrice.toString(), total: item.total.toString() }))); await recordAudit({ tableName: "purchase_orders", recordId: order.insertId, action: "create", actorId: ctx.user.id, newValue: { ...input, subtotal }, meta: getRequestMeta(ctx.req) }); return { success: true, purchaseOrderId: order.insertId, subtotal }; }),
    receive: protectedProcedure.input(idInput.merge(z.object({ items: z.array(z.object({ itemId: z.number().int().positive(), quantity: z.number().positive() })).min(1).max(500) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const order = (await db.select().from(purchaseOrders).where(eq(purchaseOrders.id, input.id)).limit(1))[0]; assertOwner(order, ctx); if (order.status === "cancelled" || order.status === "received") throw new Error("Đơn mua không còn khả dụng để nhận hàng"); const orderItems = await db.select().from(purchaseOrderItems).where(eq(purchaseOrderItems.orderId, input.id)); for (const received of input.items) { const item = orderItems.find(row => row.id === received.itemId); if (!item) throw new Error("Chi tiết đơn mua không hợp lệ"); const remaining = Number(item.quantity) - Number(item.receivedQuantity); if (received.quantity > remaining) throw new Error("Số lượng nhận vượt số lượng còn lại"); const ingredient = (await db.select().from(ingredients).where(eq(ingredients.id, item.ingredientId)).limit(1))[0]; assertOwner(ingredient, ctx); await db.update(purchaseOrderItems).set({ receivedQuantity: (Number(item.receivedQuantity) + received.quantity).toFixed(2) }).where(eq(purchaseOrderItems.id, item.id)); await db.update(ingredients).set({ stockQuantity: (Number(ingredient.stockQuantity) + received.quantity).toFixed(2) }).where(eq(ingredients.id, ingredient.id)); await db.insert(inventoryTransactions).values({ ingredientId: ingredient.id, type: "in", quantity: received.quantity.toString(), reference: order.purchaseCode, note: "Nhập từ đơn mua", createdBy: ctx.user.id }); } const refreshed = await db.select().from(purchaseOrderItems).where(eq(purchaseOrderItems.orderId, input.id)); const status = refreshed.every(item => Number(item.receivedQuantity) >= Number(item.quantity)) ? "received" : "partially_received"; await db.update(purchaseOrders).set({ status }).where(eq(purchaseOrders.id, input.id)); await recordAudit({ tableName: "purchase_orders", recordId: input.id, action: "update", actorId: ctx.user.id, newValue: { status, received: input.items }, meta: getRequestMeta(ctx.req) }); return { success: true, status }; }),
  }),
  employees: router({
    list: protectedProcedure.query(({ ctx }) => listEmployees(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    create: protectedProcedure.input(employeeInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(employees).values({ ...input, hireDate: input.hireDate, createdBy: ctx.user.id }); await recordAudit({ tableName: "employees", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, employeeId: row.insertId }; }),
    update: protectedProcedure.input(idInput.merge(employeeInput)).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(employees).where(eq(employees.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(employees).set(data).where(eq(employees.id, id)); await recordAudit({ tableName: "employees", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(employees).where(eq(employees.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(employees).where(eq(employees.id, input.id)); await recordAudit({ tableName: "employees", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  attendance: router({
    list: protectedProcedure.input(z.object({ employeeId: z.number().int().positive().optional(), from: z.coerce.date().optional(), to: z.coerce.date().optional() }).optional()).query(({ input, ctx }) => listAttendanceRecords({ ...input, ownerId: ctx.user.role === "admin" ? undefined : ctx.user.id })),
    upsert: protectedProcedure.input(attendanceInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const employee = (await db.select().from(employees).where(eq(employees.id, input.employeeId)).limit(1))[0]; assertOwner(employee, ctx); const day = new Date(Date.UTC(input.workDate.getUTCFullYear(), input.workDate.getUTCMonth(), input.workDate.getUTCDate())); const current = (await db.select().from(attendanceRecords).where(and(eq(attendanceRecords.employeeId, input.employeeId), eq(attendanceRecords.workDate, day))).limit(1))[0]; if (current) { assertOwner(current, ctx); await db.update(attendanceRecords).set({ ...input, workDate: day }).where(eq(attendanceRecords.id, current.id)); await recordAudit({ tableName: "attendance_records", recordId: current.id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, attendanceId: current.id }; } const [row] = await db.insert(attendanceRecords).values({ ...input, workDate: day, createdBy: ctx.user.id }); await recordAudit({ tableName: "attendance_records", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true, attendanceId: row.insertId }; }),
    delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(attendanceRecords).where(eq(attendanceRecords.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(attendanceRecords).where(eq(attendanceRecords.id, input.id)); await recordAudit({ tableName: "attendance_records", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  leaves: router({
    list: protectedProcedure.input(z.object({ employeeId: z.number().int().positive().optional(), status: z.enum(["pending", "approved", "rejected", "cancelled"]).optional() }).optional()).query(({ input, ctx }) => listLeaveRequests({ ...input, ownerId: ctx.user.role === "admin" ? undefined : ctx.user.id })),
    create: protectedProcedure.input(leaveCreateInput).mutation(async ({ input, ctx }) => { const totalDays = calculateInclusiveLeaveDays(input.startDate, input.endDate); if (totalDays <= 0) throw new Error("Ngày kết thúc phải từ ngày bắt đầu trở đi"); const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const employee = (await db.select().from(employees).where(eq(employees.id, input.employeeId)).limit(1))[0]; assertOwner(employee, ctx); const [row] = await db.insert(leaveRequests).values({ ...input, totalDays: totalDays.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "leave_requests", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: { ...input, totalDays }, meta: getRequestMeta(ctx.req) }); return { success: true, leaveRequestId: row.insertId, totalDays }; }),
    approve: adminProcedure.input(idInput.merge(z.object({ status: z.enum(["approved", "rejected"]) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(leaveRequests).where(eq(leaveRequests.id, input.id)).limit(1))[0]; if (!current) throw new Error("Không tìm thấy đơn nghỉ phép"); if (current.status !== "pending") throw new Error("Chỉ được duyệt đơn đang chờ xử lý"); await db.update(leaveRequests).set({ status: input.status, approvedBy: ctx.user.id, approvedAt: new Date() }).where(eq(leaveRequests.id, input.id)); await recordAudit({ tableName: "leave_requests", recordId: input.id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    cancel: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(leaveRequests).where(eq(leaveRequests.id, input.id)).limit(1))[0]; assertOwner(current, ctx); if (current.status !== "pending") throw new Error("Chỉ được hủy đơn đang chờ xử lý"); await db.update(leaveRequests).set({ status: "cancelled" }).where(eq(leaveRequests.id, input.id)); await recordAudit({ tableName: "leave_requests", recordId: input.id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: { status: "cancelled" }, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  reports: router({
    production: protectedProcedure.input(z.object({ from: z.coerce.date().optional(), to: z.coerce.date().optional() }).optional()).query(({ input, ctx }) => getProductionReport({ ...input, ownerId: ctx.user.role === "admin" ? undefined : ctx.user.id })),
    inventory: protectedProcedure.input(z.object({ from: z.coerce.date().optional(), to: z.coerce.date().optional() }).optional()).query(({ input, ctx }) => getInventoryReport({ ...input, ownerId: ctx.user.role === "admin" ? undefined : ctx.user.id })),
  }),
  ingredients: router({
    list: protectedProcedure.query(({ ctx }) => listIngredients(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    page: protectedProcedure.input(z.object({ limit: z.number().int().min(1).max(500).default(100), cursor: z.number().int().positive().optional() })).query(({ input, ctx }) => listIngredientsPage({ ...input, ownerId: ctx.user.role === "admin" ? undefined : ctx.user.id })),
    batchInsert: protectedProcedure.input(z.object({ rows: z.array(ingredientInput).min(1).max(500) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.insert(ingredients).values(input.rows.map(row => ({ ...row, stockQuantity: row.stockQuantity.toString(), lowStockThreshold: row.lowStockThreshold.toString(), createdBy: ctx.user.id }))); await recordAudit({ tableName: "ingredients", recordId: "batch", action: "batch_insert", actorId: ctx.user.id, newValue: { count: input.rows.length }, meta: getRequestMeta(ctx.req) }); return { success: true, inserted: input.rows.length }; }),
    lowStock: protectedProcedure.query(() => listLowStockIngredients()),
    transactions: protectedProcedure.query(() => listInventoryTransactions()),
    create: protectedProcedure.input(ingredientInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(ingredients).values({ ...input, stockQuantity: input.stockQuantity.toString(), lowStockThreshold: input.lowStockThreshold.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "ingredients", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return row; }),
    update: protectedProcedure.input(idInput.merge(ingredientInput)).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(ingredients).where(eq(ingredients.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(ingredients).set({ ...data, stockQuantity: data.stockQuantity.toString(), lowStockThreshold: data.lowStockThreshold.toString() }).where(eq(ingredients.id, id)); await recordAudit({ tableName: "ingredients", recordId: id, action: "update", actorId: ctx.user.id, newValue: data, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(ingredients).where(eq(ingredients.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(ingredients).where(eq(ingredients.id, input.id)); await recordAudit({ tableName: "ingredients", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    transaction: protectedProcedure.input(z.object({ ingredientId: z.number().int(), type: z.enum(["in", "out"]), quantity: z.number().positive(), reference: z.string().optional(), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const ingredient = (await db.select().from(ingredients).where(eq(ingredients.id, input.ingredientId)).limit(1))[0]; assertOwner(ingredient, ctx); const next = Number(ingredient.stockQuantity) + (input.type === "in" ? input.quantity : -input.quantity); if (next < 0) throw new Error("Tồn kho không đủ để xuất"); await db.update(ingredients).set({ stockQuantity: next.toString() }).where(eq(ingredients.id, input.ingredientId)); await db.insert(inventoryTransactions).values({ ...input, quantity: input.quantity.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "ingredients", recordId: input.ingredientId, action: "update", actorId: ctx.user.id, fieldName: "stockQuantity", oldValue: ingredient.stockQuantity, newValue: next, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  beerTypes: router({
    list: protectedProcedure.query(({ ctx }) => listBeerTypes(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    recipes: protectedProcedure.input(z.object({ beerTypeId: z.number().int().positive() })).query(({ input, ctx }) => listRecipes(input.beerTypeId, ctx.user.role === "admin" ? undefined : ctx.user.id)),
    createRecipe: protectedProcedure.input(z.object({ beerTypeId: z.number().int(), ingredientId: z.number().int(), quantity: z.number().positive(), unit: z.string().min(1) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.insert(recipes).values({ ...input, quantity: input.quantity.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "recipes", recordId: "new", action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    updateRecipe: protectedProcedure.input(idInput.merge(z.object({ quantity: z.number().positive(), unit: z.string().min(1) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(recipes).where(eq(recipes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(recipes).set({ ...data, quantity: data.quantity.toString() }).where(eq(recipes.id, id)); await recordAudit({ tableName: "recipes", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    deleteRecipe: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(recipes).where(eq(recipes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(recipes).where(eq(recipes.id, input.id)); await recordAudit({ tableName: "recipes", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    create: protectedProcedure.input(beerInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(beerTypes).values({ ...input, abv: input.abv.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "beer_types", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    update: protectedProcedure.input(idInput.merge(beerInput)).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(beerTypes).where(eq(beerTypes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(beerTypes).set({ ...data, abv: data.abv.toString() }).where(eq(beerTypes.id, id)); await recordAudit({ tableName: "beer_types", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(beerTypes).where(eq(beerTypes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(beerTypes).where(eq(beerTypes.id, input.id)); await recordAudit({ tableName: "beer_types", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  production: router({
    list: protectedProcedure.query(({ ctx }) => listProductionBatches(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    steps: protectedProcedure.input(idInput).query(({ input }) => listProductionSteps(input.id)),
    createBatch: protectedProcedure.input(z.object({ batchCode: z.string().min(1), beerTypeId: z.number().int(), plannedQuantity: z.number().positive(), notes: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [result] = await db.insert(productionBatches).values({ ...input, plannedQuantity: input.plannedQuantity.toString(), createdBy: ctx.user.id }); const batchId = result.insertId; await db.insert(productionSteps).values((['mashing', 'fermentation', 'filtration', 'bottling'] as const).map(stepType => ({ batchId, stepType, createdBy: ctx.user.id }))); await recordAudit({ tableName: "production_batches", recordId: batchId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { batchId }; }),
    updateBatch: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["planned", "in_progress", "completed", "cancelled"]).optional(), actualQuantity: z.number().nonnegative().optional(), notes: z.string().optional() }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(productionBatches).where(eq(productionBatches.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(productionBatches).set({ ...data, actualQuantity: data.actualQuantity?.toString() }).where(eq(productionBatches.id, id)); await recordAudit({ tableName: "production_batches", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    updateStep: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["pending", "in_progress", "completed"]), note: z.string().optional() }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(productionSteps).where(eq(productionSteps.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(productionSteps).set(data).where(eq(productionSteps.id, id)); await recordAudit({ tableName: "production_steps", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  customers: router({ list: protectedProcedure.query(({ ctx }) => listCustomers(ctx.user.role === "admin" ? undefined : ctx.user.id)), purchaseHistory: protectedProcedure.input(idInput).query(async ({ input }) => { const db = await getDb(); return db ? db.select().from(salesOrders).where(eq(salesOrders.customerId, input.id)).orderBy(desc(salesOrders.createdAt)) : []; }), create: protectedProcedure.input(customerInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(customers).values({ ...input, createdBy: ctx.user.id }); await recordAudit({ tableName: "customers", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true }; }), update: protectedProcedure.input(idInput.merge(customerInput)).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(customers).where(eq(customers.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(customers).set(data).where(eq(customers.id, id)); await recordAudit({ tableName: "customers", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }), delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(customers).where(eq(customers.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(customers).where(eq(customers.id, input.id)); await recordAudit({ tableName: "customers", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }) }),
  products: router({ list: protectedProcedure.query(() => listProducts()) }),
  pos: router({
    calculate: publicProcedure.input(z.object({ items: z.array(z.object({ quantity: z.number().positive(), unitPrice: z.number().nonnegative() })).min(1), discount: z.number().nonnegative().default(0), serviceFee: z.number().nonnegative().default(0), vatRate: z.number().min(0).max(100).default(0) })).query(({ input }) => { const subtotal = input.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const discount = Math.min(subtotal, input.discount); const taxable = subtotal - discount + input.serviceFee; const vat = taxable * input.vatRate / 100; return { subtotal, discount, serviceFee: input.serviceFee, vat, total: taxable + vat }; }),
    vietQrUrl: protectedProcedure.input(z.object({ bankBin: z.string().min(6), accountNumber: z.string().min(4), accountName: z.string().min(1), amount: z.number().int().nonnegative(), addInfo: z.string().optional() })).query(({ input }) => { const query = new URLSearchParams({ amount: String(input.amount), addInfo: input.addInfo ?? "Thanh toan don hang", accountName: input.accountName }); return `https://img.vietqr.io/image/${encodeURIComponent(input.bankBin)}-${encodeURIComponent(input.accountNumber)}-compact2.png?${query.toString()}`; }),
  }),
  sales: router({
    list: protectedProcedure.query(({ ctx }) => listSalesOrders(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    create: protectedProcedure.input(z.object({ orderCode: z.string().min(1), customerId: z.number().int(), items: z.array(z.object({ productId: z.number().int(), quantity: z.number().positive(), unitPrice: z.number().nonnegative() })).min(1), discount: z.number().nonnegative().default(0), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const subtotal = input.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const total = Math.max(0, subtotal - input.discount); const [result] = await db.insert(salesOrders).values({ orderCode: input.orderCode, customerId: input.customerId, subtotal: subtotal.toString(), discount: input.discount.toString(), total: total.toString(), note: input.note, createdBy: ctx.user.id }); await db.insert(salesOrderItems).values(input.items.map(item => ({ orderId: result.insertId, productId: item.productId, quantity: item.quantity.toString(), unitPrice: item.unitPrice.toString(), total: (item.quantity * item.unitPrice).toString() }))); await recordAudit({ tableName: "sales_orders", recordId: result.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { orderId: result.insertId }; }),
    receipt: protectedProcedure.input(idInput).query(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const order = (await db.select().from(salesOrders).where(eq(salesOrders.id, input.id)).limit(1))[0]; assertOwner(order, ctx); const items = await db.select().from(salesOrderItems).where(eq(salesOrderItems.orderId, input.id)); return { order, items, printedAt: new Date() }; }),
    updateStatus: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["new", "processing", "completed", "cancelled"]) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(salesOrders).where(eq(salesOrders.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.update(salesOrders).set({ status: input.status }).where(eq(salesOrders.id, input.id)); await recordAudit({ tableName: "sales_orders", recordId: input.id, action: "update", actorId: ctx.user.id, fieldName: "status", oldValue: current.status, newValue: input.status, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  workflow: router({
    list: protectedProcedure.query(({ ctx }) => listWorkflowTasks(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    create: protectedProcedure.input(z.object({ title: z.string().min(1), description: z.string().optional(), entityType: z.string().min(1), entityId: z.string().min(1), assigneeId: z.number().int().positive().optional(), dueAt: z.date().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(workflowTasks).values({ ...input, createdBy: ctx.user.id }); await recordAudit({ tableName: "workflow_tasks", recordId: row.insertId, action: "workflow", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { id: row.insertId }; }),
    updateStatus: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["open", "in_progress", "done", "cancelled"]) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.update(workflowTasks).set({ status: input.status }).where(eq(workflowTasks.id, input.id)); await recordAudit({ tableName: "workflow_tasks", recordId: input.id, action: "workflow", actorId: ctx.user.id, newValue: { status: input.status }, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  qc: router({
    standards: protectedProcedure.input(z.object({ beerTypeId: z.number().int().positive().optional() }).optional()).query(({ input }) => listQcStandards(input?.beerTypeId)),
    results: protectedProcedure.input(idInput).query(({ input }) => listQcResults(input.id)),
    batchRecord: protectedProcedure.input(z.object({ batchId: z.number().int().positive(), rows: z.array(z.object({ fieldKey: z.string().min(1), value: z.number(), note: z.string().optional() })).min(1).max(500) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const batch = (await db.select().from(productionBatches).where(eq(productionBatches.id, input.batchId)).limit(1))[0]; if (!batch) throw new Error("Không tìm thấy lô sản xuất"); const standards = await db.select().from(qcStandards).where(eq(qcStandards.beerTypeId, batch.beerTypeId)); const rows = input.rows.map(row => { const standard = resolveQcThresholdForBatch(batch, standards, row.fieldKey); const min = standard?.minValue == null ? null : Number(standard.minValue); const max = standard?.maxValue == null ? null : Number(standard.maxValue); return { batchId: input.batchId, fieldKey: row.fieldKey, value: row.value.toString(), status: evaluateQcValue(row.value, min, max), note: row.note, createdBy: ctx.user.id }; }); await db.insert(qcResults).values(rows); await recordAudit({ tableName: "qc_results", recordId: `batch-${input.batchId}`, action: "batch_insert", actorId: ctx.user.id, newValue: { count: rows.length, batchId: input.batchId }, meta: getRequestMeta(ctx.req) }); return { success: true, inserted: rows.length }; }),
    record: protectedProcedure.input(z.object({ batchId: z.number().int().positive(), fieldKey: z.string().min(1), value: z.number(), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const batch = (await db.select().from(productionBatches).where(eq(productionBatches.id, input.batchId)).limit(1))[0]; if (!batch) throw new Error("Không tìm thấy lô sản xuất"); const standards = await db.select().from(qcStandards).where(eq(qcStandards.beerTypeId, batch.beerTypeId)); const standard = resolveQcThresholdForBatch(batch, standards, input.fieldKey); const min = standard?.minValue == null ? null : Number(standard.minValue); const max = standard?.maxValue == null ? null : Number(standard.maxValue); const status = evaluateQcValue(input.value, min, max); const [row] = await db.insert(qcResults).values({ batchId: input.batchId, fieldKey: input.fieldKey, value: input.value.toString(), status, note: input.note, createdBy: ctx.user.id }); await recordAudit({ tableName: "qc_results", recordId: row.insertId, action: "create", actorId: ctx.user.id, oldValue: undefined, newValue: { ...input, status, min, max }, meta: getRequestMeta(ctx.req) }); return { id: row.insertId, status, min, max }; }),
  }),
  crossSheet: router({ links: protectedProcedure.input(z.object({ tableName: z.string().min(1), recordId: z.number().int().positive() })).query(({ input }) => getCrossSheetLinks(input)) }),
  admin: router({ users: requireAdmin.query(async () => { const db = await getDb(); return db ? db.select({ id: users.id, name: users.name, email: users.email, role: users.role, lastSignedIn: users.lastSignedIn }).from(users).orderBy(desc(users.lastSignedIn)) : []; }), audit: requireAdmin.query(() => listAuditLogs()), setRole: requireAdmin.input(z.object({ id: z.number().int().positive(), role: z.enum(["admin", "user"]) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.update(users).set({ role: input.role }).where(eq(users.id, input.id)); await recordAudit({ tableName: "users", recordId: input.id, action: "update", actorId: ctx.user.id, fieldName: "role", newValue: input.role, meta: getRequestMeta(ctx.req) }); return { success: true }; }) }),
});

export type AppRouter = typeof appRouter;
