import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { getDb, dashboardSummary, listIngredients, listIngredientsPage, listLowStockIngredients, listInventoryTransactions, listBeerTypes, listRecipes, listProductionBatches, listProductionSteps, listCustomers, listProducts, listSalesOrders, listAuditLogs, listWorkflowTasks, listQcStandards, listQcResults, selectQcStandardForBeerType } from "./db";
import { ingredients, inventoryTransactions, beerTypes, recipes, productionBatches, productionSteps, customers, beerProducts, salesOrders, salesOrderItems, users, auditLogs, workflowTasks, qcStandards, qcResults, deviceSessions } from "../drizzle/schema";
import { z } from "zod";
import { and, desc, eq } from "drizzle-orm";
import { getRequestMeta, recordAudit } from "./erp-security";

const idInput = z.object({ id: z.number().int().positive() });
const ingredientInput = z.object({ name: z.string().min(1), unit: z.string().min(1), stockQuantity: z.number().nonnegative(), lowStockThreshold: z.number().nonnegative(), supplier: z.string().optional(), notes: z.string().optional() });
const beerInput = z.object({ name: z.string().min(1), description: z.string().optional(), abv: z.number().nonnegative(), color: z.string().optional() });
const customerInput = z.object({ name: z.string().min(1), phone: z.string().optional(), address: z.string().optional(), email: z.string().optional(), notes: z.string().optional() });

const requireAdmin = protectedProcedure.use(({ ctx, next }) => {
  if (ctx.user.role !== "admin") throw new Error("Bạn không có quyền truy cập khu vực quản trị");
  return next();
});

function assertOwner(row: { createdBy?: number | null } | undefined, ctx: { user: { id: number; role: string } }) {
  if (!row) throw new Error("Không tìm thấy bản ghi");
  if (ctx.user.role !== "admin" && row.createdBy !== ctx.user.id) throw new Error("Bạn không có quyền sửa bản ghi này");
}

export function evaluateQcValue(value: number, min: number | null, max: number | null): "pass" | "fail" {
  return (min !== null && value < min) || (max !== null && value > max) ? "fail" : "pass";
}

export function resolveQcThresholdForBatch<T extends { beerTypeId: number }, S extends { beerTypeId: number; fieldKey: string }>(batch: T, standards: S[], fieldKey: string) {
  return selectQcStandardForBeerType(standards, batch.beerTypeId, fieldKey);
}

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  dashboard: router({ summary: protectedProcedure.query(() => dashboardSummary()) }),
  ingredients: router({
    list: protectedProcedure.query(({ ctx }) => listIngredients(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    page: protectedProcedure.input(z.object({ limit: z.number().int().min(1).max(500).default(100), cursor: z.number().int().positive().optional() })).query(({ input, ctx }) => listIngredientsPage({ ...input, ownerId: ctx.user.role === "admin" ? undefined : ctx.user.id })),
    batchInsert: protectedProcedure.input(z.object({ rows: z.array(ingredientInput).min(1).max(500) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.insert(ingredients).values(input.rows.map(row => ({ ...row, stockQuantity: row.stockQuantity.toString(), lowStockThreshold: row.lowStockThreshold.toString(), createdBy: ctx.user.id }))); await recordAudit({ tableName: "ingredients", recordId: "batch", action: "batch_insert", actorId: ctx.user.id, newValue: { count: input.rows.length }, meta: getRequestMeta(ctx.req) }); return { success: true, inserted: input.rows.length }; }),
    lowStock: protectedProcedure.query(() => listLowStockIngredients()),
    transactions: protectedProcedure.query(() => listInventoryTransactions()),
    create: protectedProcedure.input(ingredientInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(ingredients).values({ ...input, stockQuantity: input.stockQuantity.toString(), lowStockThreshold: input.lowStockThreshold.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "ingredients", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return row; }),
    update: protectedProcedure.input(idInput.merge(ingredientInput)).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(ingredients).where(eq(ingredients.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(ingredients).set({ ...data, stockQuantity: data.stockQuantity.toString(), lowStockThreshold: data.lowStockThreshold.toString() }).where(eq(ingredients.id, id)); await recordAudit({ tableName: "ingredients", recordId: id, action: "update", actorId: ctx.user.id, newValue: data, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(ingredients).where(eq(ingredients.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(ingredients).where(eq(ingredients.id, input.id)); await recordAudit({ tableName: "ingredients", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    transaction: protectedProcedure.input(z.object({ ingredientId: z.number().int(), type: z.enum(["in", "out"]), quantity: z.number().positive(), reference: z.string().optional(), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const ingredient = (await db.select().from(ingredients).where(eq(ingredients.id, input.ingredientId)).limit(1))[0]; assertOwner(ingredient, ctx); const next = Number(ingredient.stockQuantity) + (input.type === "in" ? input.quantity : -input.quantity); if (next < 0) throw new Error("Tồn kho không đủ để xuất"); await db.update(ingredients).set({ stockQuantity: next.toString() }).where(eq(ingredients.id, input.ingredientId)); await db.insert(inventoryTransactions).values({ ...input, quantity: input.quantity.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "ingredients", recordId: input.ingredientId, action: "update", actorId: ctx.user.id, fieldName: "stockQuantity", oldValue: ingredient.stockQuantity, newValue: next, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  beerTypes: router({
    list: protectedProcedure.query(({ ctx }) => listBeerTypes(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    recipes: protectedProcedure.input(z.object({ beerTypeId: z.number().int().positive() })).query(({ input, ctx }) => listRecipes(input.beerTypeId, ctx.user.role === "admin" ? undefined : ctx.user.id)),
    createRecipe: protectedProcedure.input(z.object({ beerTypeId: z.number().int(), ingredientId: z.number().int(), quantity: z.number().positive(), unit: z.string().min(1) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.insert(recipes).values({ ...input, quantity: input.quantity.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "recipes", recordId: "new", action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    updateRecipe: protectedProcedure.input(idInput.merge(z.object({ quantity: z.number().positive(), unit: z.string().min(1) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(recipes).where(eq(recipes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(recipes).set({ ...data, quantity: data.quantity.toString() }).where(eq(recipes.id, id)); await recordAudit({ tableName: "recipes", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    deleteRecipe: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(recipes).where(eq(recipes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(recipes).where(eq(recipes.id, input.id)); await recordAudit({ tableName: "recipes", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    create: protectedProcedure.input(beerInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(beerTypes).values({ ...input, abv: input.abv.toString(), createdBy: ctx.user.id }); await recordAudit({ tableName: "beer_types", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    update: protectedProcedure.input(idInput.merge(beerInput)).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(beerTypes).where(eq(beerTypes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(beerTypes).set({ ...data, abv: data.abv.toString() }).where(eq(beerTypes.id, id)); await recordAudit({ tableName: "beer_types", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(beerTypes).where(eq(beerTypes.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(beerTypes).where(eq(beerTypes.id, input.id)); await recordAudit({ tableName: "beer_types", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  production: router({
    list: protectedProcedure.query(({ ctx }) => listProductionBatches(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    steps: protectedProcedure.input(idInput).query(({ input }) => listProductionSteps(input.id)),
    createBatch: protectedProcedure.input(z.object({ batchCode: z.string().min(1), beerTypeId: z.number().int(), plannedQuantity: z.number().positive(), notes: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [result] = await db.insert(productionBatches).values({ ...input, plannedQuantity: input.plannedQuantity.toString(), createdBy: ctx.user.id }); const batchId = result.insertId; await db.insert(productionSteps).values((['mashing', 'fermentation', 'filtration', 'bottling'] as const).map(stepType => ({ batchId, stepType, createdBy: ctx.user.id }))); await recordAudit({ tableName: "production_batches", recordId: batchId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { batchId }; }),
    updateBatch: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["planned", "in_progress", "completed", "cancelled"]).optional(), actualQuantity: z.number().nonnegative().optional(), notes: z.string().optional() }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(productionBatches).where(eq(productionBatches.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(productionBatches).set({ ...data, actualQuantity: data.actualQuantity?.toString() }).where(eq(productionBatches.id, id)); await recordAudit({ tableName: "production_batches", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
    updateStep: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["pending", "in_progress", "completed"]), note: z.string().optional() }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(productionSteps).where(eq(productionSteps.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(productionSteps).set(data).where(eq(productionSteps.id, id)); await recordAudit({ tableName: "production_steps", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  customers: router({ list: protectedProcedure.query(({ ctx }) => listCustomers(ctx.user.role === "admin" ? undefined : ctx.user.id)), purchaseHistory: protectedProcedure.input(idInput).query(async ({ input }) => { const db = await getDb(); return db ? db.select().from(salesOrders).where(eq(salesOrders.customerId, input.id)).orderBy(desc(salesOrders.createdAt)) : []; }), create: protectedProcedure.input(customerInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(customers).values({ ...input, createdBy: ctx.user.id }); await recordAudit({ tableName: "customers", recordId: row.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { success: true }; }), update: protectedProcedure.input(idInput.merge(customerInput)).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(customers).where(eq(customers.id, input.id)).limit(1))[0]; assertOwner(current, ctx); const { id, ...data } = input; await db.update(customers).set(data).where(eq(customers.id, id)); await recordAudit({ tableName: "customers", recordId: id, action: "update", actorId: ctx.user.id, oldValue: current, newValue: data, meta: getRequestMeta(ctx.req) }); return { success: true }; }), delete: protectedProcedure.input(idInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(customers).where(eq(customers.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.delete(customers).where(eq(customers.id, input.id)); await recordAudit({ tableName: "customers", recordId: input.id, action: "delete", actorId: ctx.user.id, oldValue: current, meta: getRequestMeta(ctx.req) }); return { success: true }; }) }),
  products: router({ list: protectedProcedure.query(() => listProducts()) }),
  sales: router({
    list: protectedProcedure.query(({ ctx }) => listSalesOrders(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    create: protectedProcedure.input(z.object({ orderCode: z.string().min(1), customerId: z.number().int(), items: z.array(z.object({ productId: z.number().int(), quantity: z.number().positive(), unitPrice: z.number().nonnegative() })).min(1), discount: z.number().nonnegative().default(0), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const subtotal = input.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const total = Math.max(0, subtotal - input.discount); const [result] = await db.insert(salesOrders).values({ orderCode: input.orderCode, customerId: input.customerId, subtotal: subtotal.toString(), discount: input.discount.toString(), total: total.toString(), note: input.note, createdBy: ctx.user.id }); await db.insert(salesOrderItems).values(input.items.map(item => ({ orderId: result.insertId, productId: item.productId, quantity: item.quantity.toString(), unitPrice: item.unitPrice.toString(), total: (item.quantity * item.unitPrice).toString() }))); await recordAudit({ tableName: "sales_orders", recordId: result.insertId, action: "create", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { orderId: result.insertId }; }),
    updateStatus: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["new", "processing", "completed", "cancelled"]) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const current = (await db.select().from(salesOrders).where(eq(salesOrders.id, input.id)).limit(1))[0]; assertOwner(current, ctx); await db.update(salesOrders).set({ status: input.status }).where(eq(salesOrders.id, input.id)); await recordAudit({ tableName: "sales_orders", recordId: input.id, action: "update", actorId: ctx.user.id, fieldName: "status", oldValue: current.status, newValue: input.status, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  workflow: router({
    list: protectedProcedure.query(({ ctx }) => listWorkflowTasks(ctx.user.role === "admin" ? undefined : ctx.user.id)),
    create: protectedProcedure.input(z.object({ title: z.string().min(1), description: z.string().optional(), entityType: z.string().min(1), entityId: z.string().min(1), assigneeId: z.number().int().positive().optional(), dueAt: z.date().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const [row] = await db.insert(workflowTasks).values({ ...input, createdBy: ctx.user.id }); await recordAudit({ tableName: "workflow_tasks", recordId: row.insertId, action: "workflow", actorId: ctx.user.id, newValue: input, meta: getRequestMeta(ctx.req) }); return { id: row.insertId }; }),
    updateStatus: protectedProcedure.input(idInput.merge(z.object({ status: z.enum(["open", "in_progress", "done", "cancelled"]) }))).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.update(workflowTasks).set({ status: input.status }).where(eq(workflowTasks.id, input.id)); await recordAudit({ tableName: "workflow_tasks", recordId: input.id, action: "workflow", actorId: ctx.user.id, newValue: { status: input.status }, meta: getRequestMeta(ctx.req) }); return { success: true }; }),
  }),
  qc: router({
    standards: protectedProcedure.input(z.object({ beerTypeId: z.number().int().positive().optional() }).optional()).query(({ input }) => listQcStandards(input?.beerTypeId)),
    results: protectedProcedure.input(idInput).query(({ input }) => listQcResults(input.id)),
    record: protectedProcedure.input(z.object({ batchId: z.number().int().positive(), fieldKey: z.string().min(1), value: z.number(), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); const batch = (await db.select().from(productionBatches).where(eq(productionBatches.id, input.batchId)).limit(1))[0]; if (!batch) throw new Error("Không tìm thấy lô sản xuất"); const standards = await db.select().from(qcStandards).where(eq(qcStandards.beerTypeId, batch.beerTypeId)); const standard = resolveQcThresholdForBatch(batch, standards, input.fieldKey); const min = standard?.minValue == null ? null : Number(standard.minValue); const max = standard?.maxValue == null ? null : Number(standard.maxValue); const status = evaluateQcValue(input.value, min, max); const [row] = await db.insert(qcResults).values({ batchId: input.batchId, fieldKey: input.fieldKey, value: input.value.toString(), status, note: input.note, createdBy: ctx.user.id }); await recordAudit({ tableName: "qc_results", recordId: row.insertId, action: "create", actorId: ctx.user.id, oldValue: undefined, newValue: { ...input, status, min, max }, meta: getRequestMeta(ctx.req) }); return { id: row.insertId, status, min, max }; }),
  }),
  admin: router({ users: requireAdmin.query(async () => { const db = await getDb(); return db ? db.select({ id: users.id, name: users.name, email: users.email, role: users.role, lastSignedIn: users.lastSignedIn }).from(users).orderBy(desc(users.lastSignedIn)) : []; }), audit: requireAdmin.query(() => listAuditLogs()), setRole: requireAdmin.input(z.object({ id: z.number().int().positive(), role: z.enum(["admin", "user"]) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database chưa sẵn sàng"); await db.update(users).set({ role: input.role }).where(eq(users.id, input.id)); await recordAudit({ tableName: "users", recordId: input.id, action: "update", actorId: ctx.user.id, fieldName: "role", newValue: input.role, meta: getRequestMeta(ctx.req) }); return { success: true }; }) }),
});

export type AppRouter = typeof appRouter;
